//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullProgram
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegajosVehiculare
    {
        public int Id { get; set; }
        public int Caja { get; set; }
        public int IdVehiculo { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string Usuario { get; set; }
        public int SubCaja { get; set; }
        public string Imagen { get; set; }
    
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
